long_list=[{'key': 'constantKey',
  'int': 81,
  'bool': True,
  'list': [5, 7, 5],
  'tup': (2, 6),
  'nested_dict': {'rtPTc': 82, 'SjfiU': 95, 'qtSIo': 45}},
 {'key': 'constantKey',
  'int': 5,
  'bool': True,
  'list': [5, 10, 5],
  'tup': (1, 9),
  'nested_dict': {'IkqUk': 56, 'EeHAc': 42, 'HyisS': 20}},
 {'key': 'constantKey',
  'int': 32,
  'bool': False,
  'list': [2, 3, 4],
  'tup': (10, 10),
  'nested_dict': {'XINwd': 95, 'WyqJv': 52, 'OcgdT': 94}},
 {'key': 'constantKey',
  'int': 32,
  'bool': False,
  'list': [10, 10, 4],
  'tup': (7, 5),
  'nested_dict': {'rQCrk': 49, 'XXDfQ': 63, 'uVqDj': 68}},
 {'key': 'constantKey',
  'int': 74,
  'bool': False,
  'list': [8, 2, 10],
  'tup': (6, 8),
  'nested_dict': {'wkBkN': 80, 'wUZWm': 6, 'YbYDo': 23}}]